### ISSUE TITLE
Option for private class level variables with getters/setters.

### ISSUE THREAD

**Issue by MegaMattMiller** [javiercbk/json_to_dart#1]
It would be great if we could have the option to make all variables private, and generate getters/setters for them. Great tool either way!

**Comment by javiercbk** [comment]
To be honest, I'm some kind of a noob here. I've been playing around with Dart for a week or two, so I'm not exactly sure what are the convention regarding Dart classes.

In Java I would have created private instance variables and have their getters and setters generated, but for Dart I decided to go for the [flutter approach](https://flutter.io/json/#serializing-json-manually-using-dartconvert) which uses public instance vars.

I'll leave this issue open for a while and if more developers agree that this is the way to go, I'll implement it as a gift for the community.

Thanks for your comment!

**Comment by MegaMattMiller** [comment]
Sounds like a plan. I'll fork the repo and play around a bit. Normally how I handle data classes is everything is private, with getters. And only things that I know will need to change later get setters.

**Comment by javiercbk** [comment]
Probably I will be addressing this issue shortly while making [this](https://github.com/javiercbk/json_to_dart/issues/2) change

**Comment by javiercbk** [comment]
Fixed with this [PR](https://github.com/javiercbk/json_to_dart/pull/4). Will update the official page shortly

**Comment by MegaMattMiller** [comment]
Fantastic! Will be using this at work tomorrow!
