### ISSUE TITLE
Unable to parse json 

### ISSUE THREAD

**Issue by shakil807g** [javiercbk/json_to_dart#10]
`{
	"glossary": {
		"title": "example glossary",
		"GlossDiv": {
			"title": "S",
			"GlossList": {
				"GlossEntry": {
					"ID": "SGML",
					"SortAs": "SGML",
					"GlossTerm": "Standard Generalized Markup Language",
					"Acronym": "SGML",
					"Abbrev": "ISO 8879:1986",
					"GlossDef": {
						"para": "A meta-markup language, used to create markup languages such as DocBook.",
						"GlossSeeAlso": ["GML", "XML"]
					},
					"GlossSee": "markup"
				}
			}
		}
	}
}`

copy this json and put it in box  and it unable to parse it .

**Comment by shakil807g** [comment]
But great tool when it works

**Comment by javiercbk** [comment]
I will fix it shortly. Thanks for reporting

**Comment by javiercbk** [comment]
fixed in #11

**Comment by shakil807g** [comment]
wow thanks
