### ISSUE TITLE
Please add input to change the Autogenerated  class name

### ISSUE THREAD

**Issue by shakil807g** [javiercbk/json_to_dart#15]

**Comment by javiercbk** [comment]
I'll add it when I have some time, in the mean time you can do so executing this library in your environment. To do so, take a look at this [example](https://github.com/javiercbk/json_to_dart/blob/master/example/generate_model_example.dart)

**Comment by lizhuoyuan** [comment]
want too.

**Comment by paulorobertocruz** [comment]
Someone is working on this in https://github.com/javiercbk/json_to_dart/pull/31.

**Comment by javiercbk** [comment]
Ok, I'll try to merge this today. Sorry for the delay

**Comment by javiercbk** [comment]
Added this feature among other error checking features
