### ISSUE TITLE
Cannot generate dart code. Please check the project caveats.

### ISSUE THREAD

**Issue by iharshb** [javiercbk/json_to_dart#16]
I am trying to generate JSON to dart  for this JSON : 

[https://jsonplaceholder.typicode.com/users](url)

**Comment by javiercbk** [comment]
There seems to be an issue when the root element is an array. Try to paste the first object and you'll get at least the object parser. Generating the parser for the array should be almost trivial.

**Comment by morningstarwang** [comment]
I won't consider it as a bug. It seems a basic rule to take an **object** rather than **array** as the root element.

**Comment by javiercbk** [comment]
The library could handle this scenario, there is certainly room for improvement here.

**Comment by javiercbk** [comment]
Fixed the array as root element problem
