### ISSUE TITLE
why this json have an issue?

### ISSUE THREAD

**Issue by followthemoney1** [javiercbk/json_to_dart#18]
I don't understand why this json have an issue?

![image](https://user-images.githubusercontent.com/8526612/51281884-55903080-19ec-11e9-80a6-962eb95cc041.png)
![image](https://user-images.githubusercontent.com/8526612/51281892-5d4fd500-19ec-11e9-8bad-68029caa512c.png)

**Comment by javiercbk** [comment]
Check [this issue](https://github.com/javiercbk/json_to_dart/issues/16). Yo cannot have an array as root element, try using only the first element.
