### ISSUE TITLE
Constants should be used instead of plain strings

### ISSUE THREAD

**Issue by vanlooverenkoen** [javiercbk/json_to_dart#19]
Is it possible to add the hardcoded strings a constants at the top of the file? That way it is easier to use them in combination with a database to specify your columns. SqFlite,...

![image](https://user-images.githubusercontent.com/21172855/52535814-366a9180-2d53-11e9-89e6-04e2a7c6f454.png)

**Comment by javiercbk** [comment]
It is possible to do so, but I would not add them in the top of the file but rather as static variables.

I don't know for what purpose you might want to access those fields but I can think of a select statement where you would like to select the proper fields using the class "fields list" (providing they match your database table column names).

The static fields should be optional (like the private fields options) and they should provide a way to list the fields. I would like to further understand your needs so I can make improvements to this tool based on real world scenarios and not my hypothetical use cases :smiley:
