### ISSUE TITLE
希望可以做成vscode扩展

### ISSUE THREAD

**Issue by lifetin** [javiercbk/json_to_dart#20]
> 希望可以做成vscode扩展
> 可以右键选中JSON, 输名类名称,一键生成代码.

I hope I can make a vscode extension.
You can right-click on JSON, enter the name of the class, and generate the code with one click.

**Comment by javiercbk** [comment]
That would be great, but it is out of scope of this project. Anybody can create such project and use this library.

> 那会很棒，但这超出了这个项目的范围。 任何人都可以创建这样的项目并使用这个库。
