### ISSUE TITLE
Excuse me.help,please.

### ISSUE THREAD

**Issue by pheromone** [javiercbk/json_to_dart#21]
部分格式的json数据无法转换.比如 :
Partial json data cannot be converted. For example:

http://tingapi.ting.baidu.com/v1/restserver/ting?method=baidu.ting.billboard.billList&type=2&size=10&offset=0

![image](https://user-images.githubusercontent.com/14305431/54894813-78acf400-4ef7-11e9-8a72-37046452b603.png)

**Comment by javiercbk** [comment]
I can generate the code without any issue. Could you provide further explanaition of the issue?

![cannot-find-error-json](https://user-images.githubusercontent.com/1448426/54929817-e86daf80-4ef4-11e9-969c-16179f8361e3.png)

> 我可以毫无问题地生成代码。 你能否提供有关问题的进一步解释？

**Comment by pheromone** [comment]
thank you
