### ISSUE TITLE
Not generating full class structure

### ISSUE THREAD

**Issue by koalas8** [javiercbk/json_to_dart#33]
![批注 2019-08-08 184351](https://user-images.githubusercontent.com/4694450/62697282-f425c280-ba0c-11e9-9ad2-449407a3a8d7.png)

**Comment by javiercbk** [comment]
Could you please post the JSON in the bug report? I could replicate it but I had to copy it by hand.

**Comment by koalas8** [comment]
> Could you please post the JSON in the bug report? I could replicate it but I had to copy it by hand.

{ "glossary": { "title": "example glossary", "GlossDiv": { "title": "S", "GlossList": { "GlossEntry": { "ID": "SGML", "SortAs": "SGML", "GlossTerm": "Standard Generalized Markup Language", "Acronym": "SGML", "Abbrev": "ISO 8879:1986", "GlossDef": { "para": "A meta-markup language, used to create markup languages such as DocBook.", "GlossSeeAlso": ["GML", "XML"] }, "GlossSee": "markup" } } } } }

The JSON is copied from here:  [https://github.com/javiercbk/json_to_dart/issues/10](https://github.com/javiercbk/json_to_dart/issues/10)

**Comment by koalas8** [comment]
Here is another JSON:

{
    "msg": "success",
    "code": 0,
    "data": {
        "bankCard": {
            "bankName": "民生银行",
            "bankAccount": "6210000001835706",
            "bankAccountName": "张三",
            "bankPhone": "158******75"
        },
        "list": [
            {
                "id": "5E98159351CD417BBB9AE1FBCBCB22EF",
                "merchantId": null,
                "bankName": "招商银行",
                "bankCode": "308",
                "thawTrx": null
            }
        ]
    }
}

**Comment by koalas8** [comment]
Here is another JSON：

`{
    "msg": "success",
    "code": 0,
    "data": {
        "bankCard": {
            "bankName": "民生银行",
            "bankAccount": "6210000001835706",
            "bankAccountName": "张三",
            "bankPhone": "158******75"
        },
        "list": [
            {
                "id": "5E98159351CD417BBB9AE1FBCBCB22EF",
                "merchantId": null,
                "bankName": "招商银行",
                "bankCode": "308",
                "thawTrx": null
            }
        ]
    }
}`

**Comment by javiercbk** [comment]
I'm so sorry. I've tried to insert a new feature and screw this up. It is fixed now

**Comment by koalas8** [comment]
Thanks for your hard work.
