### ISSUE TITLE
Unable to generate a complete mechanism Lack of class

### ISSUE THREAD

**Issue by jahnli** [javiercbk/json_to_dart#34]
Unable to generate a complete mechanism Lack of class

![QQ截图20190809172833](https://user-images.githubusercontent.com/20943608/62769367-60ff9200-bacb-11e9-98e7-f8fc949b0bc1.png)
![QQ截图20190809172816](https://user-images.githubusercontent.com/20943608/62769371-62c95580-bacb-11e9-9813-443886b864e9.png)

When I'm done copying, I'm prompted that I'm missing a class

![QQ截图20190809173027](https://user-images.githubusercontent.com/20943608/62769403-78d71600-bacb-11e9-8f72-f121f4ad32dd.png)

**Comment by jahnli** [comment]
{
    "config": {
        "searchUrl": "https://m.ctrip.com/restapi/h5api/searchapp/search?source=mobileweb&action=autocomplete&contentType=json&keyword=1"
    },
    "localNavList": [
        {
            "icon": "http://www.devio.org/io/flutter_app/img/ln_ticket.png",
            "title": "景点·玩乐",
            "url": "https://m.ctrip.com/html5/ticket/",
            "statusBarColor": "19A0F0",
            "hideAppBar": true
        },
        {
            "icon": "http://www.devio.org/io/flutter_app/img/ln_guide.png",
            "title": "当地攻略",
            "url": "https://m.ctrip.com/webapp/you/",
            "statusBarColor": "19A0F0",
            "hideAppBar": true
        }
    ],
    "salesBox": {
        "icon": "http://www.devio.org/io/flutter_app/img/sales_box_huodong.png",
        "moreUrl": "https://contents.ctrip.com/activitysetupapp/mkt/index/moreact",
        "bigCard1": {
            "icon": "https://dimg04.c-ctrip.com/images/700t0y000000m71h523FE_375_260_342.png",
            "url": "https://contents.ctrip.com/buildingblocksweb/special/membershipcard/index.html?sceneid=1&productid=14912&ishidenavbar=yes&pushcode=act_svip_hm31",
            "title": "活动"
        },
        "bigCard2": {
            "icon": "https://dimg04.c-ctrip.com/images/700a10000000portu2BAD_375_260_342.jpg",
            "url": "https://m.ctrip.com/webapp/you/livestream/plan/crhHotelList.html?liveAwaken=true&isHideHeader=true&isHideNavBar=YES&mktcrhcode=hotevent",
            "title": "活动"
        }
    }
}

**Comment by javiercbk** [comment]
Sorry, I've fixed this
