### ISSUE TITLE
Null safety not support and 'List' constructor is not abiavle

### ISSUE THREAD

**Issue by BabySatan5282** [javiercbk/json_to_dart#70]
It need to upgrade for support null safety and List deprecated. Thanks .

**Comment by thana19** [comment]
[https://thana.in.th/2021/06/20/fix-null-safety-not-support-json_to_dart/](url)

**Comment by dingjianjaja** [comment]
use this https://dingjianjaja.github.io

**Comment by javiercbk** [comment]
you really spammed your work here....I like it...also, I've implemented this feature because people were starting to get angry...I don't know why though
