### ISSUE TITLE
Sir can you make it for null safety for flutter 2.2.0

### ISSUE THREAD

**Issue by Kalyanb447-github** [javiercbk/json_to_dart#73]

**Comment by skar-helper** [comment]
Here's what needs to be changed: https://stackoverflow.com/questions/67065621/flutter-null-safety-with-fromjson

This is likely just 5 mins of work.

**Comment by javiercbk** [comment]
done...it was a 12 hours of work

**Comment by Kalyanb447-github** [comment]
thank you sir
