### ISSUE TITLE
not work at

### ISSUE THREAD

**Issue by sintak** [javiercbk/json_to_dart#8]
not work at:
{
    "x": {
        "q": [],
        "t": [],
        "e": [
            {}
        ]
    }
}

**Comment by javiercbk** [comment]
Will fix that shortly

**Comment by javiercbk** [comment]
Fixed in #13 
The code generated by this library will be invalid though. Avoid:
* Empty objects
* Empty Arrays
* null
Also remember that lis library grabs the first element of an array as a sample to generate classes, other elements will be ignored.
