### ISSUE TITLE
Update output on invalid input

### ISSUE THREAD

**Issue by kevmoo** [javiercbk/json_to_dart#9]
See 

```json
{"bob":true,"thing": {"class": "Kevin"}}
```

There is a lot of screaming in the terminal, but no user-visible error.

**Comment by javiercbk** [comment]
Thanks, I will take a look at it in the weekend along with the other open issue. I'll add a simple red message on invalid input

**Comment by kevmoo** [comment]
Sounds good!

**Comment by javiercbk** [comment]
Fixed in #13 
The code generated by this library will be invalid though. Avoid:
* Empty objects
* Empty Arrays
* null
Also remember that lis library grabs the first element of an array as a sample to generate classes, other elements will be ignored.
